---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: python:3.12-alpine
  commands:
  - pip3 config set global.index-url https://mirror.sjtu.edu.cn/pypi/web/simple
  - pip3 install poetry==1.7.0
  - poetry install --no-root
  - poetry run mkdocs build

- name: scp files
  image: appleboy/drone-scp
  settings:
    host:
      - 10.50.249.2
    user: admin
    key:
      from_secret: ssh_key
    port: 22
    command_timeout: 2m
    target: /home/admin/findmirror/
    source:
      - site/*
    rm: true

node:
  lxc: "110"