site_name: 觅镜 FindMirror
copyright: |
  Copyright &copy; 2023 - 2024 Jin Zhijie, <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh-hans" target="_blank">CC BY-SA 4.0</a>
  <br>
  <a href="https://beian.miit.gov.cn/" target="_blank">沪ICP备2021021453号-3</a>

theme:
  name: material
  language: zh
  logo: assets/taffy-light.svg
  favicon: assets/taffy-dark-border-indigo.svg
  palette:
  # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - navigation.sections
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.path
    - navigation.expand
    - navigation.top
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - content.tooltips
    
nav:
  - 'index.md'
  - '镜像':
    - 'apt.md'
    - 'alpine.md'
    - 'python.md'
    - 'ros2.md'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      auto_title: true
      linenums: true
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      combine_header_slug: true
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
  - attr_list
  - md_in_html
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - admonition
  - def_list
  - toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:

plugins:
  - search
  - macros
  - include-markdown
  - glightbox

extra_javascript:
  - javascripts/extra.js